name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Compress Images
        uses: calibreapp/image-actions@master
        if: github.event_name == 'pull_request'
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: npm i

      - name: Build
        run: npm run build
